// Ordinarily, you'd generate this data from markdown files in your
// repo, or fetch them from a database of some kind. But in order to
// avoid unnecessary dependencies in the starter template, and in the
// service of obviousness, we're just going to leave it here.

// This file is called `_balls.js` rather than `balls.js`, because
// we don't want to create an `/blog/balls` route — the leading
// underscore tells Sapper not to do that.

const balls = [
    {
        name: 'Classic',
        slug: 'classic',
        img: '',
        dataSet: [
            { id: 0, text: '00', desc: 'Huevos' },
            { id: 1, text: '01', desc: 'Agua' },
            { id: 2, text: '02', desc: 'Niño' },
            { id: 3, text: '03', desc: 'San Cono' },
            { id: 4, text: '04', desc: 'La cama' },
            { id: 5, text: '05', desc: 'Gato' },
            { id: 6, text: '06', desc: 'Perro' },
            { id: 7, text: '07', desc: 'Revolver' },
            { id: 8, text: '08', desc: 'Incendio' },
            { id: 9, text: '09', desc: 'Arroyo' },
            { id: 10, text: '10', desc: 'La leche' },
            { id: 11, text: '11', desc: 'Minero' },
            { id: 12, text: '12', desc: 'Soldado' },
            { id: 13, text: '13', desc: 'La yeta' },
            { id: 14, text: '14', desc: 'Borracho' },
            { id: 15, text: '15', desc: 'Niña bonita' },
            { id: 16, text: '16', desc: 'Anillo' },
            { id: 17, text: '17', desc: 'Desgracia' },
            { id: 18, text: '18', desc: 'Sangre' },
            { id: 19, text: '19', desc: 'Pescado' },
            { id: 20, text: '20', desc: 'La fiesta' },
            { id: 21, text: '21', desc: 'Mujer' },
            { id: 22, text: '22', desc: 'Loco' },
            { id: 23, text: '23', desc: 'Cocinero' },
            { id: 24, text: '24', desc: 'Caballo' },
            { id: 25, text: '25', desc: 'Gallina' },
            { id: 26, text: '26', desc: 'La Misa' },
            { id: 27, text: '27', desc: 'El peine' },
            { id: 28, text: '28', desc: 'El cerro' },
            { id: 29, text: '29', desc: 'San Pedro' },
            { id: 30, text: '30', desc: 'Santa Rosa' },
            { id: 31, text: '31', desc: 'La luz' },
            { id: 32, text: '32', desc: 'Dinero' },
            { id: 33, text: '33', desc: 'Cristo' },
            { id: 34, text: '34', desc: 'La cabeza' },
            { id: 35, text: '35', desc: 'Pajarito' },
            { id: 36, text: '36', desc: 'La manteca' },
            { id: 37, text: '37', desc: 'El dentista' },
            { id: 38, text: '38', desc: 'Piedras' },
            { id: 39, text: '39', desc: 'Lluvia' },
            { id: 40, text: '40', desc: 'El cura' },
            { id: 41, text: '41', desc: 'El cuchillo' },
            { id: 42, text: '42', desc: 'Zapatillas' },
            { id: 43, text: '43', desc: 'Balcón' },
            { id: 44, text: '44', desc: 'La Cárcel' },
            { id: 45, text: '45', desc: 'El vino' },
            { id: 46, text: '46', desc: 'Tomates' },
            { id: 47, text: '47', desc: 'Muerto' },
            { id: 48, text: '48', desc: 'Muerto que habla' },
            { id: 49, text: '49', desc: 'La carne' },
            { id: 50, text: '50', desc: 'El pan' },
            { id: 51, text: '51', desc: 'Serrucho' },
            { id: 52, text: '52', desc: 'Madre e hijo' },
            { id: 53, text: '53', desc: 'El barco' },
            { id: 54, text: '54', desc: 'La vaca' },
            { id: 55, text: '55', desc: 'La música' },
            { id: 56, text: '56', desc: 'La caída' },
            { id: 57, text: '57', desc: 'El jorobado' },
            { id: 58, text: '58', desc: 'Ahogado' },
            { id: 59, text: '59', desc: 'Las plantas' },
            { id: 60, text: '60', desc: 'La virgen' },
            { id: 61, text: '61', desc: 'Escopeta' },
            { id: 62, text: '62', desc: 'Inundación' },
            { id: 63, text: '63', desc: 'Casamiento' },
            { id: 64, text: '64', desc: 'Llanto' },
            { id: 65, text: '65', desc: 'El cazador' },
            { id: 66, text: '66', desc: 'Lombriz' },
            { id: 67, text: '67', desc: 'Mordida' },
            { id: 68, text: '68', desc: 'Sobrinos' },
            { id: 69, text: '69', desc: 'Vicios' },
            { id: 70, text: '70', desc: 'Muerto Sueño' },
            { id: 71, text: '71', desc: 'Excremento' },
            { id: 72, text: '72', desc: 'Sorpresa' },
            { id: 73, text: '73', desc: 'Hospital' },
            { id: 74, text: '74', desc: 'Gente Negra' },
            { id: 75, text: '75', desc: 'Los besos' },
            { id: 76, text: '76', desc: 'Las llamas' },
            { id: 77, text: '77', desc: 'Pierna Mujer' },
            { id: 78, text: '78', desc: 'Ramera' },
            { id: 79, text: '79', desc: 'Ladrón' },
            { id: 80, text: '80', desc: 'La bocha' },
            { id: 81, text: '81', desc: 'Las flores' },
            { id: 82, text: '82', desc: 'La pelea' },
            { id: 83, text: '83', desc: 'Mal tiempo' },
            { id: 84, text: '84', desc: 'La iglesia' },
            { id: 85, text: '85', desc: 'Linterna' },
            { id: 86, text: '86', desc: 'El humo' },
            { id: 87, text: '87', desc: 'Piojos' },
            { id: 88, text: '88', desc: 'El papa' },
            { id: 89, text: '89', desc: 'La rata' },
            { id: 90, text: '90', desc: 'El miedo' },
            { id: 91, text: '91', desc: 'Excusado' },
            { id: 92, text: '92', desc: 'El médico' },
            { id: 93, text: '93', desc: 'Enamorado' },
            { id: 94, text: '94', desc: 'Cementerio' },
            { id: 95, text: '95', desc: 'Anteojos' },
            { id: 96, text: '96', desc: 'Marido' },
            { id: 97, text: '97', desc: 'Mesa' },
            { id: 98, text: '98', desc: 'Lavandera' },
            { id: 99, text: '99', desc: 'Hermano' },
        ]
    },
    {
        name: 'League Of Legends',
        slug: 'lol',
        img: '',
        dataSet: [
            { id: 1, text: '1', desc: '1' },
            { id: 2, text: '2', desc: '2' },
            { id: 3, text: '3', desc: '3' },
            { id: 4, text: '4', desc: '4' },
            { id: 5, text: '5', desc: '5' },
            { id: 6, text: '6', desc: '6' },
            { id: 7, text: '7', desc: '7' },
            { id: 8, text: '8', desc: '8' },
            { id: 9, text: '9', desc: '9' },
            { id: 10, text: '10', desc: '10' },
            { id: 11, text: '11', desc: '11' },
            { id: 12, text: '12', desc: '12' },
            { id: 13, text: '13', desc: '13' },
            { id: 14, text: '14', desc: '14' },
            { id: 15, text: '15', desc: '15' },
            { id: 16, text: '16', desc: '16' },
            { id: 17, text: '17', desc: '17' },
            { id: 18, text: '18', desc: '18' },
            { id: 19, text: '19', desc: '19' },
            { id: 20, text: '20', desc: '20' },
            { id: 21, text: '21', desc: '21' },
            { id: 22, text: '22', desc: '22' },
            { id: 23, text: '23', desc: '23' },
            { id: 24, text: '24', desc: '24' },
            { id: 25, text: '25', desc: '25' },
            { id: 26, text: '26', desc: '26' },
            { id: 27, text: '27', desc: '27' },
            { id: 28, text: '28', desc: '28' },
            { id: 29, text: '29', desc: '29' },
            { id: 30, text: '30', desc: '30' },
            { id: 31, text: '31', desc: '31' },
            { id: 32, text: '32', desc: '32' },
            { id: 33, text: '33', desc: '33' },
            { id: 34, text: '34', desc: '34' },
            { id: 35, text: '35', desc: '35' },
            { id: 36, text: '36', desc: '36' },
            { id: 37, text: '37', desc: '37' },
            { id: 38, text: '38', desc: '38' },
            { id: 39, text: '39', desc: '39' },
            { id: 40, text: '40', desc: '40' },
            { id: 41, text: '41', desc: '41' },
            { id: 42, text: '42', desc: '42' },
            { id: 43, text: '43', desc: '43' },
            { id: 44, text: '44', desc: '44' },
            { id: 45, text: '45', desc: '45' },
            { id: 46, text: '46', desc: '46' },
            { id: 47, text: '47', desc: '47' },
            { id: 48, text: '48', desc: '48' },
            { id: 49, text: '49', desc: '49' },
            { id: 50, text: '50', desc: '50' },
            { id: 51, text: '51', desc: '51' },
            { id: 52, text: '52', desc: '52' },
            { id: 53, text: '53', desc: '53' },
            { id: 54, text: '54', desc: '54' },
            { id: 55, text: '55', desc: '55' },
            { id: 56, text: '56', desc: '56' },
            { id: 57, text: '57', desc: '57' },
            { id: 58, text: '58', desc: '58' },
            { id: 59, text: '59', desc: '59' },
            { id: 60, text: '60', desc: '60' },
            { id: 61, text: '61', desc: '61' },
            { id: 62, text: '62', desc: '62' },
            { id: 63, text: '63', desc: '63' },
            { id: 64, text: '64', desc: '64' },
            { id: 65, text: '65', desc: '65' },
            { id: 66, text: '66', desc: '66' },
            { id: 67, text: '67', desc: '67' },
            { id: 68, text: '68', desc: '68' },
            { id: 69, text: '69', desc: '69' },
            { id: 70, text: '70', desc: '70' },
            { id: 71, text: '71', desc: '71' },
            { id: 72, text: '72', desc: '72' },
            { id: 73, text: '73', desc: '73' },
            { id: 74, text: '74', desc: '74' },
            { id: 75, text: '75', desc: '75' },
            { id: 76, text: '76', desc: '76' },
            { id: 77, text: '77', desc: '77' },
            { id: 78, text: '78', desc: '78' },
            { id: 79, text: '79', desc: '79' },
            { id: 80, text: '80', desc: '80' },
            { id: 81, text: '81', desc: '81' },
            { id: 82, text: '82', desc: '82' },
            { id: 83, text: '83', desc: '83' },
            { id: 84, text: '84', desc: '84' },
            { id: 85, text: '85', desc: '85' },
            { id: 86, text: '86', desc: '86' },
            { id: 87, text: '87', desc: '87' },
            { id: 88, text: '88', desc: '88' },
            { id: 89, text: '89', desc: '89' },
            { id: 90, text: '90', desc: '90' },
            { id: 91, text: '91', desc: '91' },
            { id: 92, text: '92', desc: '92' },
            { id: 93, text: '93', desc: '93' },
            { id: 94, text: '94', desc: '94' },
            { id: 95, text: '95', desc: '95' },
            { id: 96, text: '96', desc: '96' },
            { id: 97, text: '97', desc: '97' },
            { id: 98, text: '98', desc: '98' },
            { id: 99, text: '99', desc: '99' },
            { id: 100, text: '100', desc: '100' }
        ]
    },
    {
        name: 'Pokémon',
        slug: 'pokemon',
        img: '',
        dataSet: [
            { id: 1, text: '1', desc: '1' },
            { id: 2, text: '2', desc: '2' },
            { id: 3, text: '3', desc: '3' },
            { id: 4, text: '4', desc: '4' },
            { id: 5, text: '5', desc: '5' },
            { id: 6, text: '6', desc: '6' },
            { id: 7, text: '7', desc: '7' },
            { id: 8, text: '8', desc: '8' },
            { id: 9, text: '9', desc: '9' },
            { id: 10, text: '10', desc: '10' },
            { id: 11, text: '11', desc: '11' },
            { id: 12, text: '12', desc: '12' },
            { id: 13, text: '13', desc: '13' },
            { id: 14, text: '14', desc: '14' },
            { id: 15, text: '15', desc: '15' },
            { id: 16, text: '16', desc: '16' },
            { id: 17, text: '17', desc: '17' },
            { id: 18, text: '18', desc: '18' },
            { id: 19, text: '19', desc: '19' },
            { id: 20, text: '20', desc: '20' },
            { id: 21, text: '21', desc: '21' },
            { id: 22, text: '22', desc: '22' },
            { id: 23, text: '23', desc: '23' },
            { id: 24, text: '24', desc: '24' },
            { id: 25, text: '25', desc: '25' },
            { id: 26, text: '26', desc: '26' },
            { id: 27, text: '27', desc: '27' },
            { id: 28, text: '28', desc: '28' },
            { id: 29, text: '29', desc: '29' },
            { id: 30, text: '30', desc: '30' },
            { id: 31, text: '31', desc: '31' },
            { id: 32, text: '32', desc: '32' },
            { id: 33, text: '33', desc: '33' },
            { id: 34, text: '34', desc: '34' },
            { id: 35, text: '35', desc: '35' },
            { id: 36, text: '36', desc: '36' },
            { id: 37, text: '37', desc: '37' },
            { id: 38, text: '38', desc: '38' },
            { id: 39, text: '39', desc: '39' },
            { id: 40, text: '40', desc: '40' },
            { id: 41, text: '41', desc: '41' },
            { id: 42, text: '42', desc: '42' },
            { id: 43, text: '43', desc: '43' },
            { id: 44, text: '44', desc: '44' },
            { id: 45, text: '45', desc: '45' },
            { id: 46, text: '46', desc: '46' },
            { id: 47, text: '47', desc: '47' },
            { id: 48, text: '48', desc: '48' },
            { id: 49, text: '49', desc: '49' },
            { id: 50, text: '50', desc: '50' },
            { id: 51, text: '51', desc: '51' },
            { id: 52, text: '52', desc: '52' },
            { id: 53, text: '53', desc: '53' },
            { id: 54, text: '54', desc: '54' },
            { id: 55, text: '55', desc: '55' },
            { id: 56, text: '56', desc: '56' },
            { id: 57, text: '57', desc: '57' },
            { id: 58, text: '58', desc: '58' },
            { id: 59, text: '59', desc: '59' },
            { id: 60, text: '60', desc: '60' },
            { id: 61, text: '61', desc: '61' },
            { id: 62, text: '62', desc: '62' },
            { id: 63, text: '63', desc: '63' },
            { id: 64, text: '64', desc: '64' },
            { id: 65, text: '65', desc: '65' },
            { id: 66, text: '66', desc: '66' },
            { id: 67, text: '67', desc: '67' },
            { id: 68, text: '68', desc: '68' },
            { id: 69, text: '69', desc: '69' },
            { id: 70, text: '70', desc: '70' },
            { id: 71, text: '71', desc: '71' },
            { id: 72, text: '72', desc: '72' },
            { id: 73, text: '73', desc: '73' },
            { id: 74, text: '74', desc: '74' },
            { id: 75, text: '75', desc: '75' },
            { id: 76, text: '76', desc: '76' },
            { id: 77, text: '77', desc: '77' },
            { id: 78, text: '78', desc: '78' },
            { id: 79, text: '79', desc: '79' },
            { id: 80, text: '80', desc: '80' },
            { id: 81, text: '81', desc: '81' },
            { id: 82, text: '82', desc: '82' },
            { id: 83, text: '83', desc: '83' },
            { id: 84, text: '84', desc: '84' },
            { id: 85, text: '85', desc: '85' },
            { id: 86, text: '86', desc: '86' },
            { id: 87, text: '87', desc: '87' },
            { id: 88, text: '88', desc: '88' },
            { id: 89, text: '89', desc: '89' },
            { id: 90, text: '90', desc: '90' },
            { id: 91, text: '91', desc: '91' },
            { id: 92, text: '92', desc: '92' },
            { id: 93, text: '93', desc: '93' },
            { id: 94, text: '94', desc: '94' },
            { id: 95, text: '95', desc: '95' },
            { id: 96, text: '96', desc: '96' },
            { id: 97, text: '97', desc: '97' },
            { id: 98, text: '98', desc: '98' },
            { id: 99, text: '99', desc: '99' },
            { id: 100, text: '100', desc: '100' }
        ]
    },
];

balls.forEach(set => {
    set.dataSet.forEach(b => { b.checked = false; });
});

export default balls;
