// Ordinarily, you'd generate this data from markdown files in your
// repo, or fetch them from a database of some kind. But in order to
// avoid unnecessary dependencies in the starter template, and in the
// service of obviousness, we're just going to leave it here.

// This file is called `_balls.js` rather than `balls.js`, because
// we don't want to create an `/blog/balls` route — the leading
// underscore tells Sapper not to do that.

const balls = [
    {
        name: 'Classic',
        slug: 'classic',
        img: '',
        dataSet: [
            { id: 0, text: '00', desc: 'Huevos' },
            { id: 1, text: '01', desc: 'Agua' },
            { id: 2, text: '02', desc: 'Niño' },
            { id: 3, text: '03', desc: 'San Cono' },
            { id: 4, text: '04', desc: 'La cama' },
            { id: 5, text: '05', desc: 'Gato' },
            { id: 6, text: '06', desc: 'Perro' },
            { id: 7, text: '07', desc: 'Revolver' },
            { id: 8, text: '08', desc: 'Incendio' },
            { id: 9, text: '09', desc: 'Arroyo' },
            { id: 10, text: '10', desc: 'La leche' },
            { id: 11, text: '11', desc: 'Minero' },
            { id: 12, text: '12', desc: 'Soldado' },
            { id: 13, text: '13', desc: 'La yeta' },
            { id: 14, text: '14', desc: 'Borracho' },
            { id: 15, text: '15', desc: 'Niña bonita' },
            { id: 16, text: '16', desc: 'Anillo' },
            { id: 17, text: '17', desc: 'Desgracia' },
            { id: 18, text: '18', desc: 'Sangre' },
            { id: 19, text: '19', desc: 'Pescado' },
            { id: 20, text: '20', desc: 'La fiesta' },
            { id: 21, text: '21', desc: 'Mujer' },
            { id: 22, text: '22', desc: 'Loco' },
            { id: 23, text: '23', desc: 'Cocinero' },
            { id: 24, text: '24', desc: 'Caballo' },
            { id: 25, text: '25', desc: 'Gallina' },
            { id: 26, text: '26', desc: 'La Misa' },
            { id: 27, text: '27', desc: 'El peine' },
            { id: 28, text: '28', desc: 'El cerro' },
            { id: 29, text: '29', desc: 'San Pedro' },
            { id: 30, text: '30', desc: 'Santa Rosa' },
            { id: 31, text: '31', desc: 'La luz' },
            { id: 32, text: '32', desc: 'Dinero' },
            { id: 33, text: '33', desc: 'Cristo' },
            { id: 34, text: '34', desc: 'La cabeza' },
            { id: 35, text: '35', desc: 'Pajarito' },
            { id: 36, text: '36', desc: 'La manteca' },
            { id: 37, text: '37', desc: 'El dentista' },
            { id: 38, text: '38', desc: 'Piedras' },
            { id: 39, text: '39', desc: 'Lluvia' },
            { id: 40, text: '40', desc: 'El cura' },
            { id: 41, text: '41', desc: 'El cuchillo' },
            { id: 42, text: '42', desc: 'Zapatillas' },
            { id: 43, text: '43', desc: 'Balcón' },
            { id: 44, text: '44', desc: 'La Cárcel' },
            { id: 45, text: '45', desc: 'El vino' },
            { id: 46, text: '46', desc: 'Tomates' },
            { id: 47, text: '47', desc: 'Muerto' },
            { id: 48, text: '48', desc: 'Muerto que habla' },
            { id: 49, text: '49', desc: 'La carne' },
            { id: 50, text: '50', desc: 'El pan' },
            { id: 51, text: '51', desc: 'Serrucho' },
            { id: 52, text: '52', desc: 'Madre e hijo' },
            { id: 53, text: '53', desc: 'El barco' },
            { id: 54, text: '54', desc: 'La vaca' },
            { id: 55, text: '55', desc: 'La música' },
            { id: 56, text: '56', desc: 'La caída' },
            { id: 57, text: '57', desc: 'El jorobado' },
            { id: 58, text: '58', desc: 'Ahogado' },
            { id: 59, text: '59', desc: 'Las plantas' },
            { id: 60, text: '60', desc: 'La virgen' },
            { id: 61, text: '61', desc: 'Escopeta' },
            { id: 62, text: '62', desc: 'Inundación' },
            { id: 63, text: '63', desc: 'Casamiento' },
            { id: 64, text: '64', desc: 'Llanto' },
            { id: 65, text: '65', desc: 'El cazador' },
            { id: 66, text: '66', desc: 'Lombriz' },
            { id: 67, text: '67', desc: 'Mordida' },
            { id: 68, text: '68', desc: 'Sobrinos' },
            { id: 69, text: '69', desc: 'Vicios' },
            { id: 70, text: '70', desc: 'Muerto Sueño' },
            { id: 71, text: '71', desc: 'Excremento' },
            { id: 72, text: '72', desc: 'Sorpresa' },
            { id: 73, text: '73', desc: 'Hospital' },
            { id: 74, text: '74', desc: 'Gente Negra' },
            { id: 75, text: '75', desc: 'Los besos' },
            { id: 76, text: '76', desc: 'Las llamas' },
            { id: 77, text: '77', desc: 'Pierna Mujer' },
            { id: 78, text: '78', desc: 'Ramera' },
            { id: 79, text: '79', desc: 'Ladrón' },
            { id: 80, text: '80', desc: 'La bocha' },
            { id: 81, text: '81', desc: 'Las flores' },
            { id: 82, text: '82', desc: 'La pelea' },
            { id: 83, text: '83', desc: 'Mal tiempo' },
            { id: 84, text: '84', desc: 'La iglesia' },
            { id: 85, text: '85', desc: 'Linterna' },
            { id: 86, text: '86', desc: 'El humo' },
            { id: 87, text: '87', desc: 'Piojos' },
            { id: 88, text: '88', desc: 'El papa' },
            { id: 89, text: '89', desc: 'La rata' },
            { id: 90, text: '90', desc: 'El miedo' },
            { id: 91, text: '91', desc: 'Excusado' },
            { id: 92, text: '92', desc: 'El médico' },
            { id: 93, text: '93', desc: 'Enamorado' },
            { id: 94, text: '94', desc: 'Cementerio' },
            { id: 95, text: '95', desc: 'Anteojos' },
            { id: 96, text: '96', desc: 'Marido' },
            { id: 97, text: '97', desc: 'Mesa' },
            { id: 98, text: '98', desc: 'Lavandera' },
            { id: 99, text: '99', desc: 'Hermano' },
        ]
    },
    {
        name: 'Emojis',
        slug: 'emojis',
        img: '',
        dataSet: [
            { id: 0, text: '😀', desc: 'feliz' },
            { id: 1, text: '🤣', desc: 'carcajada' },
            { id: 2, text: '😂', desc: 'lagrimas de felicidad' },
            { id: 3, text: '🙃', desc: 'cara del reves' },
            { id: 4, text: '😉', desc: 'guinando el ojo' },
            { id: 5, text: '😍', desc: 'ojos corazones' },
            { id: 6, text: '😋', desc: 'delicioso' },
            { id: 7, text: '🤪', desc: 'cara de loco' },
            { id: 8, text: '🤐', desc: 'boca cremallera' },
            { id: 9, text: '🙄', desc: 'ojos en blanco' },
            { id: 10, text: '🤥', desc: 'cara de mentir' },
            { id: 11, text: '😪', desc: 'somnoliento' },
            { id: 12, text: '🤤', desc: 'cara que babea' },
            { id: 13, text: '😴', desc: 'durmiendo' },
            { id: 14, text: '😷', desc: 'cara con mascarilla' },
            { id: 15, text: '🤢', desc: 'cara de nauseas' },
            { id: 16, text: '🤧', desc: 'cara que estornuda' },
            { id: 17, text: '🥵', desc: 'cara sudorosa' },
            { id: 18, text: '🥶', desc: 'cara congelada' },
            { id: 19, text: '🤯', desc: 'cara con cabeza explosiva' },
            { id: 20, text: '😎', desc: 'guay' },
            { id: 21, text: '☹️', desc: 'cara muy triste' },
            { id: 22, text: '😭', desc: 'llorando fuerte' },
            { id: 23, text: '😱', desc: 'cara atemorizada' },
            { id: 24, text: '😓', desc: 'sudor frio' },
            { id: 25, text: '😤', desc: 'cara de mucho enfado' },
            { id: 26, text: '🤬', desc: 'cara con simbolos sobre la boca' },
            { id: 27, text: '😈', desc: 'sonrisa con cuernos' },
            { id: 28, text: '💀', desc: 'calavera' },
            { id: 29, text: '💩', desc: 'caca con ojos' },
            { id: 30, text: '🤡', desc: 'cara de payaso' },
            { id: 31, text: '👻', desc: 'fantasma' },
            { id: 32, text: '👽', desc: 'cara de alienigena' },
            { id: 33, text: '👾', desc: 'cara monstruo alienigena' },
            { id: 34, text: '🤖', desc: 'cara robot' },
            { id: 35, text: '😺', desc: 'gato sonriendo' },
            { id: 36, text: '😻', desc: 'gato sonriendo corazones' },
            { id: 37, text: '🙀', desc: 'gato asustado' },
            { id: 38, text: '🙈', desc: 'no ve el mal' },
            { id: 39, text: '🙉', desc: 'no oye el mal' },
            { id: 40, text: '🙊', desc: 'no dice el mal' },
            { id: 41, text: '❤️', desc: 'corazon' },
            { id: 42, text: '💚', desc: 'corazon verde envidia' },
            { id: 43, text: '💙', desc: 'corazon azul tristeza' },
            { id: 44, text: '💯', desc: 'pleno' },
            { id: 45, text: '💣', desc: 'bomba' },
            { id: 46, text: '✌️', desc: 'mano victoria' },
            { id: 47, text: '🤞', desc: 'dedos cruzados' },
            { id: 48, text: '🤟', desc: 'gesto de mano te amo' },
            { id: 49, text: '🤘', desc: 'mano cuernos' },
            { id: 50, text: '🤙', desc: 'gesto de llamar' },
            { id: 51, text: '🖕', desc: 'dedo corazon hacia arriba' },
            { id: 52, text: '👏', desc: 'manos haciendo palmas' },
            { id: 53, text: '🙌', desc: 'hurra' },
            { id: 54, text: '🙏', desc: 'manos en oracion' },
            { id: 55, text: '💅', desc: 'aplicacion esmalte unas' },
            { id: 56, text: '💪', desc: 'biceps' },
            { id: 57, text: '👅', desc: 'lengua' },
            { id: 58, text: '👄', desc: 'boca' },
            { id: 59, text: '👶', desc: 'cara de bebe' },
            { id: 60, text: '👳', desc: 'cara hombre con turbante' },
            { id: 61, text: '👼', desc: 'cara de angelito' },
            { id: 62, text: '🎅', desc: 'papa noel' },
            { id: 63, text: '🧙‍♂️', desc: 'mago' },
            { id: 64, text: '🧟', desc: 'zombi persona' },
            { id: 65, text: '🐸', desc: 'cara de rana' },
            { id: 66, text: '🐌', desc: 'caracol' },
            { id: 67, text: '🍅', desc: 'tomate' },
            { id: 68, text: '🥑', desc: 'aguacate' },
            { id: 69, text: '🍆', desc: 'berenjena' },
            { id: 70, text: '🥔', desc: 'patata' },
            { id: 71, text: '🥕', desc: 'zanahoria' },
            { id: 72, text: '🌽', desc: 'espiga de maiz' },
            { id: 73, text: '🌶️', desc: 'chile picante' },
            { id: 74, text: '🥒', desc: 'pepino' },
            { id: 75, text: '🥦', desc: 'brocoli brecol' },
            { id: 76, text: '🍄', desc: 'champinon' },
            { id: 77, text: '🍔', desc: 'hamburguesa' },
            { id: 78, text: '🌭', desc: 'perrito caliente' },
            { id: 79, text: '🌮', desc: 'taco' },
            { id: 80, text: '🌯', desc: 'burrito' },
            { id: 81, text: '🍤', desc: 'gamba frita' },
            { id: 82, text: '🥟', desc: 'dumpling' },
            { id: 83, text: '🍩', desc: 'rosquilla' },
            { id: 84, text: '🍪', desc: 'galleta' },
            { id: 85, text: '🍰', desc: 'pedazo de tarta' },
            { id: 86, text: '🧁', desc: 'cupcake 3' },
            { id: 87, text: '🍮', desc: 'flan' },
            { id: 88, text: '☕', desc: 'bebida caliente' },
            { id: 89, text: '🍺', desc: 'cerveza' },
            { id: 90, text: '🧃', desc: 'tetrabrik' },
            { id: 91, text: '🧉', desc: 'mate' },
            { id: 92, text: '✈️', desc: 'avion' },
            { id: 93, text: '🚀', desc: 'cohete' },
            { id: 94, text: '🌙', desc: 'luna' },
            { id: 95, text: '☀️', desc: 'sol' },
            { id: 96, text: '🌈', desc: 'arcoiris' },
            { id: 97, text: '🔥', desc: 'fuego' },
            { id: 98, text: '🌊', desc: 'ola de mar' },
            { id: 99, text: '💊', desc: 'comprimido' }
        ]
    },
    {
        name: 'League of Legends',
        slug: 'lol',
        img: '',
        dataSet: [
            { id: 0, text: 'Aatrox', desc: 'Aatrox the Darkin Blade', img: 'lol/ball/aatrox.webp', cardImg: 'lol/card/aatrox.png' },
            { id: 1, text: 'Ahri', desc: 'Ahri The Nine-Tailed Fox', img: 'lol/ball/ahri.webp', cardImg: 'lol/card/ahri.jfif' },
            { id: 2, text: 'Akali', desc: 'Akali The Rogue Assassin', img: 'lol/ball/akali.webp', cardImg: 'lol/card/akali.jfif' },
            { id: 3, text: 'Alistar', desc: 'Alistar The Minotaur', img: 'lol/ball/alistar.webp', cardImg: 'lol/card/alistar.jfif' },
            { id: 4, text: 'Amumu', desc: 'Amumu The Sad Mummy', img: 'lol/ball/amumu.webp', cardImg: 'lol/card/amumu.jfif' },
            { id: 5, text: 'Anivia', desc: 'Anivia The Cryophoenix', img: 'lol/ball/anivia.webp', cardImg: 'lol/card/anivia.jfif' },
            { id: 6, text: 'Annie', desc: 'Annie The Dark Child', img: 'lol/ball/annie.webp', cardImg: 'lol/card/annie.jfif' },
            { id: 7, text: 'Aphelios', desc: 'Aphelios The Weapon of the Faithful', img: 'lol/ball/aphelios.webp', cardImg: 'lol/card/aphelios.jfif' },
            { id: 8, text: 'Ashe', desc: 'Ashe The Frost Archer', img: 'lol/ball/ashe.webp', cardImg: 'lol/card/ashe.jfif' },
            { id: 9, text: 'Aurelion', desc: 'Aurelion The Star Forger', img: 'lol/ball/aurelion-sol.webp', cardImg: 'lol/card/aurelion-sol.jfif' },
            { id: 10, text: 'Azir', desc: 'Azir The Emperor of the Sands', img: 'lol/ball/azir.webp', cardImg: 'lol/card/azir.jfif' },
            { id: 11, text: 'Bard', desc: 'Bard The Wandering Caretaker', img: 'lol/ball/bard.webp', cardImg: 'lol/card/bard.jfif' },
            { id: 12, text: 'Blitzcrank', desc: 'Blitzcrank The Great Steam Golem', img: 'lol/ball/blitzcrank.webp', cardImg: 'lol/card/blitzcrank.jfif' },
            { id: 13, text: 'Brand', desc: 'Brand The Burning Vengeance', img: 'lol/ball/brand.webp', cardImg: 'lol/card/brand.jfif' },
            { id: 14, text: 'Braum', desc: 'Braum the Heart of the Freljord', img: 'lol/ball/braum.webp', cardImg: 'lol/card/braum.jfif' },
            { id: 15, text: 'Caitlyn', desc: 'Caitlyn The Sheriff of Piltover', img: 'lol/ball/caitlyn.webp', cardImg: 'lol/card/caitlyn.jfif' },
            { id: 16, text: 'Camille', desc: 'Camille The Steel Shadow', img: 'lol/ball/camille.webp', cardImg: 'lol/card/camille.jfif' },
            { id: 17, text: 'Cassiopeia', desc: 'Cassiopeia The Serpent\'s Embrace', img: 'lol/ball/cassiopeia.webp', cardImg: 'lol/card/cassiopeia.jfif' },
            { id: 18, text: 'Cho Gath', desc: 'Cho Gath The Terror of the Void', img: 'lol/ball/chogath.webp', cardImg: 'lol/card/chogath.jfif' },
            { id: 19, text: 'Corki', desc: 'Corki The Daring Bombardier', img: 'lol/ball/corki.webp', cardImg: 'lol/card/corki.jfif' },
            { id: 20, text: 'Darius', desc: 'Darius The Hand of Noxus', img: 'lol/ball/darius.webp', cardImg: 'lol/card/darius.jfif' },
            { id: 21, text: 'Diana', desc: 'Diana The Scorn of the Moon', img: 'lol/ball/diana.webp', cardImg: 'lol/card/diana.jfif' },
            { id: 22, text: 'Dr Mundo', desc: 'The Madman of Zaun', img: 'lol/ball/dr-mundo.webp', cardImg: 'lol/card/dr-mundo.jfif' },
            { id: 23, text: 'Draven', desc: 'Draven The Glorious Executioner', img: 'lol/ball/draven.webp', cardImg: 'lol/card/draven.jfif' },
            { id: 24, text: 'Ekko', desc: 'Ekko The Boy Who Shattered Time', img: 'lol/ball/ekko.webp', cardImg: 'lol/card/ekko.jfif' },
            { id: 25, text: 'Elise', desc: 'Elise The Spider Queen', img: 'lol/ball/elise.webp', cardImg: 'lol/card/elise.jfif' },
            { id: 26, text: 'Evelynn', desc: 'Evelynn Agony\'s Embrace', img: 'lol/ball/evelynn.webp', cardImg: 'lol/card/evelynn.jfif' },
            { id: 27, text: 'Ezreal', desc: 'Ezreal The Prodigal Explorer', img: 'lol/ball/ezreal.webp', cardImg: 'lol/card/ezreal.jfif' },
            { id: 28, text: 'Fiddlesticks', desc: 'Fiddlesticks The Ancient Fear', img: 'lol/ball/fiddlesticks.webp', cardImg: 'lol/card/fiddlesticks.jfif' },
            { id: 29, text: 'Fiora', desc: 'Fiora The Grand Duelist', img: 'lol/ball/fiora.webp', cardImg: 'lol/card/fiora.jfif' },
            { id: 30, text: 'Fizz', desc: 'Fizz The Tidal Trickster', img: 'lol/ball/fizz.webp', cardImg: 'lol/card/fizz.jfif' },
            { id: 31, text: 'Galio', desc: 'Galio The Colossus', img: 'lol/ball/galio.webp', cardImg: 'lol/card/galio.jfif' },
            { id: 32, text: 'Gangplank', desc: 'Gangplank The Saltwater Scourge', img: 'lol/ball/gangplank.webp', cardImg: 'lol/card/gangplank.jfif' },
            { id: 33, text: 'Garen', desc: 'Garen The Might of Demacia', img: 'lol/ball/garen.webp', cardImg: 'lol/card/garen.jfif' },
            { id: 34, text: 'Gnar', desc: 'Gnar The Missing Link', img: 'lol/ball/gnar.webp', cardImg: 'lol/card/gnar.jfif' },
            { id: 35, text: 'Gragas', desc: 'Gragas The Rabble Rouser', img: 'lol/ball/gragas.webp', cardImg: 'lol/card/gragas.jfif' },
            { id: 36, text: 'Graves', desc: 'Graves The Outlaw', img: 'lol/ball/graves.webp', cardImg: 'lol/card/graves.jfif' },
            { id: 37, text: 'Hecarim', desc: 'Hecarim The Shadow of War', img: 'lol/ball/hecarim.webp', cardImg: 'lol/card/hecarim.jfif' },
            { id: 38, text: 'Heimerdinger', desc: 'Heimerdinger The Revered Inventor', img: 'lol/ball/heimerdinger.webp', cardImg: 'lol/card/heimerdinger.jfif' },
            { id: 39, text: 'Illaoi', desc: 'Illaoi The Kraken Priestess', img: 'lol/ball/illaoi.webp', cardImg: 'lol/card/illaoi.jfif' },
            { id: 40, text: 'Irelia', desc: 'Irelia The Blade Dancer', img: 'lol/ball/irelia.webp', cardImg: 'lol/card/irelia.jfif' },
            { id: 41, text: 'Ivern', desc: 'Ivern The Green Father', img: 'lol/ball/ivern.webp', cardImg: 'lol/card/ivern.jfif' },
            { id: 42, text: 'Janna', desc: 'Janna The Storm\'s Fury', img: 'lol/ball/janna.webp', cardImg: 'lol/card/janna.jfif' },
            { id: 43, text: 'Jarvan IV', desc: 'Jarvan IV The Exemplar of Demacia', img: 'lol/ball/jarvan-iv.webp', cardImg: 'lol/card/jarvan-iv.jfif' },
            { id: 44, text: 'Jax', desc: 'Jax Grandmaster at Arms', img: 'lol/ball/jax.webp', cardImg: 'lol/card/jax.jfif' },
            { id: 45, text: 'Jayce', desc: 'Jayce The Defender of Tomorrow', img: 'lol/ball/jayce.webp', cardImg: 'lol/card/jayce.jfif' },
            { id: 46, text: 'Jhin', desc: 'Jhin The Virtuoso', img: 'lol/ball/jhin.webp', cardImg: 'lol/card/jhin.jfif' },
            { id: 47, text: 'Jinx', desc: 'Jinx the Loose Cannon', img: 'lol/ball/jinx.webp', cardImg: 'lol/card/jinx.jfif' },
            { id: 48, text: 'Kai Sa', desc: 'Kai Sa Daughter of the Void', img: 'lol/ball/kaisa.webp', cardImg: 'lol/card/kaisa.jfif' },
            { id: 49, text: 'Kalista', desc: 'Kalista The Spear of Vengeance', img: 'lol/ball/kalista.webp', cardImg: 'lol/card/kalista.jfif' },
            { id: 50, text: 'Karma', desc: 'Karma The Enlightened One', img: 'lol/ball/karma.webp', cardImg: 'lol/card/karma.jfif' },
            { id: 51, text: 'Karthus', desc: 'Karthus The Deathsinger', img: 'lol/ball/karthus.webp', cardImg: 'lol/card/karthus.jfif' },
            { id: 52, text: 'Kassadin', desc: 'Kassadin The Void Walker', img: 'lol/ball/kassadin.webp', cardImg: 'lol/card/kassadin.jfif' },
            { id: 53, text: 'Katarina', desc: 'Katarina The Sinister Blade', img: 'lol/ball/katarina.webp', cardImg: 'lol/card/katarina.jfif' },
            { id: 54, text: 'Kayle', desc: 'Kayle The Righteous', img: 'lol/ball/kayle.png', cardImg: 'lol/card/kayle.jfif' },
            { id: 55, text: 'Kayn', desc: 'Kayn The Shadow Reaper', img: 'lol/ball/kayn.webp', cardImg: 'lol/card/kayn.jfif' },
            { id: 56, text: 'Kennen', desc: 'Kennen The Heart of the Tempest', img: 'lol/ball/kennen.webp', cardImg: 'lol/card/kennen.jfif' },
            { id: 57, text: 'Kha Zix', desc: 'Kha Zix The Voidreaver', img: 'lol/ball/khazix.webp', cardImg: 'lol/card/khazix.jfif' },
            { id: 58, text: 'Kindred', desc: 'Kindred The Eternal Hunters', img: 'lol/ball/kindred.webp', cardImg: 'lol/card/kindred.jfif' },
            { id: 59, text: 'Kled', desc: 'Kled The Cantankerous Cavalier', img: 'lol/ball/kled.webp', cardImg: 'lol/card/kled.jfif' },
            { id: 60, text: 'Kog Maw', desc: 'Kog Maw The Mouth of the Abyss', img: 'lol/ball/kogmaw.webp', cardImg: 'lol/card/kogmaw.jfif' },
            { id: 61, text: 'LeBlanc', desc: 'LeBlanc The Deceiver', img: 'lol/ball/leblanc.webp', cardImg: 'lol/card/leblanc.jfif' },
            { id: 62, text: 'Lee Sin', desc: 'Lee Sin The Blind Monk', img: 'lol/ball/lee-sin.webp', cardImg: 'lol/card/lee-sin.jfif' },
            { id: 63, text: 'Leona', desc: 'Leona The Radiant Dawn', img: 'lol/ball/leona.webp', cardImg: 'lol/card/leona.jfif' },
            { id: 64, text: 'Lissandra', desc: 'Lissandra the Ice Witch', img: 'lol/ball/lissandra.webp', cardImg: 'lol/card/lissandra.jfif' },
            { id: 65, text: 'Lucian', desc: 'Lucian the Purifier', img: 'lol/ball/lucian.webp', cardImg: 'lol/card/lucian.jfif' },
            { id: 66, text: 'Lulu', desc: 'Lulu The Fae Sorceress', img: 'lol/ball/lulu.webp', cardImg: 'lol/card/lulu.jfif' },
            { id: 67, text: 'Lux', desc: 'Lux The Lady of Luminosity', img: 'lol/ball/lux.webp', cardImg: 'lol/card/lux.jfif' },
            { id: 68, text: 'Malphite', desc: 'Malphite Shard of the Monolith', img: 'lol/ball/malphite.webp', cardImg: 'lol/card/malphite.jfif' },
            { id: 69, text: 'Malzahar', desc: 'Malzahar The Prophet of the Void', img: 'lol/ball/malzahar.webp', cardImg: 'lol/card/malzahar.jfif' },
            { id: 70, text: 'Maokai', desc: 'Maokai The Twisted Treant', img: 'lol/ball/maokai.webp', cardImg: 'lol/card/maokai.jfif' },
            { id: 71, text: 'Master Yi', desc: 'Master Yi The Wuju Bladesman', img: 'lol/ball/master-yi.webp', cardImg: 'lol/card/master-yi.jfif' },
            { id: 72, text: 'Miss Fortune', desc: 'Miss Fortune The Bounty Hunter', img: 'lol/ball/miss-fortune.webp', cardImg: 'lol/card/miss-fortune.jfif' },
            { id: 73, text: 'Mordekaiser', desc: 'Mordekaiser The Iron Revenant', img: 'lol/ball/mordekaiser.webp', cardImg: 'lol/card/mordekaiser.jfif' },
            { id: 74, text: 'Morgana', desc: 'Morgana The Fallen', img: 'lol/ball/morgana.png', cardImg: 'lol/card/morgana.jfif' },
            { id: 75, text: 'Nami', desc: 'Nami the Tidecaller', img: 'lol/ball/nami.webp', cardImg: 'lol/card/nami.jfif' },
            { id: 76, text: 'Nasus', desc: 'Nasus The Curator of the Sands', img: 'lol/ball/nasus.webp', cardImg: 'lol/card/nasus.jfif' },
            { id: 77, text: 'Nautilus', desc: 'Nautilus The Titan of the Depths', img: 'lol/ball/nautilus.webp', cardImg: 'lol/card/nautilus.jfif' },
            { id: 78, text: 'Neeko', desc: 'Neeko The Curious Chameleon', img: 'lol/ball/neeko.webp', cardImg: 'lol/card/neeko.jfif' },
            { id: 79, text: 'Nidalee', desc: 'Nidalee The Bestial Huntress', img: 'lol/ball/nidalee.webp', cardImg: 'lol/card/nidalee.jfif' },
            { id: 80, text: 'Nocturne', desc: 'Nocturne The Eternal Nightmare', img: 'lol/ball/nocturne.webp', cardImg: 'lol/card/nocturne.jfif' },
            { id: 81, text: 'Nunu & Willump', desc: 'Nunu & Willump <span>The Boy and His Yeti', img: 'lol/ball/nunu-amp-willump.webp', cardImg: 'lol/card/nunu-amp-willump.jfif' },
            { id: 82, text: 'Olaf', desc: 'Olaf The Berserker', img: 'lol/ball/olaf.webp', cardImg: 'lol/card/olaf.jfif' },
            { id: 83, text: 'Orianna', desc: 'Orianna The Lady of Clockwork', img: 'lol/ball/orianna.webp', cardImg: 'lol/card/orianna.jfif' },
            { id: 84, text: 'Ornn', desc: 'Ornn The Fire Below The Mountain', img: 'lol/ball/ornn.webp', cardImg: 'lol/card/ornn.jfif' },
            { id: 85, text: 'Pantheon', desc: 'Pantheon The Unbreakable Spear', img: 'lol/ball/pantheon.webp', cardImg: 'lol/card/pantheon.jfif' },
            { id: 86, text: 'Poppy', desc: 'Poppy Keeper of the Hammer', img: 'lol/ball/poppy.webp', cardImg: 'lol/card/poppy.jfif' },
            { id: 87, text: 'Pyke', desc: 'Pyke The Bloodharbor Ripper', img: 'lol/ball/pyke.webp', cardImg: 'lol/card/pyke.jfif' },
            { id: 88, text: 'Qiyana', desc: 'Qiyana Empress of the Elements', img: 'lol/ball/qiyana.webp', cardImg: 'lol/card/qiyana.jfif' },
            { id: 89, text: 'Quinn', desc: 'Quinn Demacia\'s Wings', img: 'lol/ball/quinn.webp', cardImg: 'lol/card/quinn.jfif' },
            { id: 90, text: 'Rakan', desc: 'Rakan The Charmer', img: 'lol/ball/rakan.png', cardImg: 'lol/card/rakan.jfif' },
            { id: 91, text: 'Rammus', desc: 'Rammus The Armordillo', img: 'lol/ball/rammus.webp', cardImg: 'lol/card/rammus.jfif' },
            { id: 92, text: 'Rek Sai', desc: 'Rek Sai The Void Burrower', img: 'lol/ball/reksai.webp', cardImg: 'lol/card/reksai.jfif' },
            { id: 93, text: 'Renekton', desc: 'Renekton The Butcher of the Sands', img: 'lol/ball/renekton.webp', cardImg: 'lol/card/renekton.jfif' },
            { id: 94, text: 'Rengar', desc: 'Rengar The Pridestalker', img: 'lol/ball/rengar.webp', cardImg: 'lol/card/rengar.jfif' },
            { id: 95, text: 'Riven', desc: 'Riven The Exile', img: 'lol/ball/riven.webp', cardImg: 'lol/card/riven.jfif' },
            { id: 96, text: 'Rumble', desc: 'Rumble The Mechanized Menace', img: 'lol/ball/rumble.webp', cardImg: 'lol/card/rumble.jfif' },
            { id: 97, text: 'Ryze', desc: 'Ryze The Rogue Mage', img: 'lol/ball/ryze.webp', cardImg: 'lol/card/ryze.jfif' },
            { id: 98, text: 'Sejuani', desc: 'Sejuani Fury of the North', img: 'lol/ball/sejuani.webp', cardImg: 'lol/card/sejuani.jfif' },
            { id: 99, text: 'Senna', desc: 'Senna The Redeemer', img: 'lol/ball/senna.webp', cardImg: 'lol/card/senna.jfif' }
        ]
    },
];

balls.forEach(set => {
    set.dataSet.forEach(b => { b.checked = false; });
});

export default balls;
